name:                LambdaTrader
version:             0.1.0.0
author:              "Adam Wasiak"
maintainer:          "adamwasiak55@gmail.com"
copyright:           "2026 Adam Wasiak"

description:         "LambdaTrader - a terminal chatbot that parses natural language into structured requests, backed by persistent memory and live stock market data via a third-party finance API."


language:    GHC2021

# This is the list of dependencies you should modify to add packages
# to your application.
dependencies:
- base >= 4.7 && < 5
- megaparsec
- ansi-terminal
- containers
- mtl
- time
- request
- aeson
- bytestring
- filepath
- directory

default-extensions:
- TypeSynonymInstances
- FlexibleInstances
- RecordWildCards
- LambdaCase


library:
  source-dirs: src

executables:
  LambdaTrader-tui:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LambdaTrader
    when:        
    - condition: false        
      other-modules: Paths_LambdaTrader

tests:
  LambdaTrader-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options: []
    dependencies:
    - LambdaTrader
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - QuickCheck
    - bytestring
    - split
    - temporary
    - regex-tdfa
    - text
    when:        
    - condition: false        
      other-modules: Paths_LambdaTrader